.idea/.gitignore
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
OpenAI-Trip-Planner.iml
README.md
src/data_access/InMemoryUserDataAccessObject.java

Based off of PaulGries' file structure example... a test to see if my local project directory works!

Added file structure

---

apiDocuments/getBusiness.md
apiDocuments/searchBusiness.md

Add detailed description of the two main Yelp Fusion functions that we need

Updated Documentation for Yelp Fusion

---

src/entity/Dayplan.java
src/entity/Events.java
src/entity/User.java

in the process of making activities and meals inherit from events, and added dayplan and user class

Event (unfinished) and User classes added 

---

src/main/java/use_case/UserSignupInputBoundary.java
src/main/java/use_case/UserSignupInputData.java
src/main/java/use_case/UserSignupInteractor.java
src/main/java/use_case/UserSignupOutputBoundary.java
src/main/java/use_case/UserSignupOutputData.java

This is a draft. We should add UserFactory to the entity before modifying this further.

Add draft for UserSignup (Output, Input data and boundary)

---

src/main/java/api/ChatGPT.java
src/main/java/api/GPTInterface.java

Update ChatGPT API object

---

src/main/java/entity/Activity.java
src/main/java/entity/Business.java
src/main/java/entity/Meal.java

fixed the attributes for Business, Meals and Activities. Tests not written yet :(

Changed Business attributes

---

src/main/java/api/OpenAI.java
src/main/java/api/OpenInterface.java
src/main/java/api/YelpFusion.java
src/main/java/api/YelpInterface.java
src/test/java/api/OpenAITest.java

fix a typo for javadoc in YelpFusion, implemented the OpenAI API.

Implemented OpenAI API.

---

src/main/java/entity/DayplanFactory.java
src/main/java/entity/UserFactory.java

Add DayplanFactory interface

---

src/main/java/entity/Activity.java
src/main/java/entity/Business.java
src/main/java/entity/BusinessFactory.java
src/main/java/entity/Meal.java
src/main/java/entity/YelpBusinessFactory.java
src/main/java/use_case/user/UserSignupInteractor.java
src/test/java/entity/BusinessFactoryTest.java
src/test/java/entity/YelpBusinessFactoryTest.java

change rating to float (it should be float), I might miss some places so please change rating to float whenever u still see it as string. finished BusinessFactory and its test

Janice javadoc and factories

---

src/main/java/interface_adapter/DayplanViewModel.java
src/main/java/view/DayplanView.java

Modified methods in DayplanViewModel

Add DayplanView interactions with console

---

src/main/java/interface_adapter/DayplanViewModel.java
src/test/java/interface_adapter/DayplanViewModelTest.java

Add tests for DayplanViewModel

---

README.md

this may be something to consider in the future on protecting passwords

Add note in readme

---

src/main/java/use_case/distance/DistanceInputBoundary.java
src/main/java/use_case/distance/DistanceInputData.java
src/main/java/use_case/distance/DistanceInteractor.java
src/test/java/use_case/distance/DistanceInteractorTest.java

DistanceInteractor now has finished execute method which returns the difference in the two coordinates in Km.

Joshua distance calculator

---

src/main/java/app/UserLoginUseCaseFactory.java
src/main/java/data_access/UserLoginDataAccessInterface.java
src/main/java/data_access/UserLoginDataAccessObject.java
src/main/java/interface_adapter/Login/LoginController.java
src/main/java/interface_adapter/Login/LoginPresenter.java
src/main/java/interface_adapter/Login/LoginViewModel.java
src/main/java/use_case/user_login/UserLoginInputBoundary.java
src/main/java/use_case/user_login/UserLoginInputData.java
src/main/java/use_case/user_login/UserLoginInteractor.java
src/main/java/use_case/user_login/UserLoginOutputBoundary.java
src/main/java/use_case/user_login/UserLoginOutputData.java
src/main/java/view/UserLoginView.java

Set up files for Login Use Case

---

src/main/java/use_case/user_login/UserLoginInteractor.java

not sure what happened, but it says it was not committed on my end.

implemented UserLoginInteractor

---

src/main/java/interface_adapter/Login/LoginController.java
src/main/java/interface_adapter/Login/LoginPresenter.java
src/main/java/use_case/user_login/UserLoginInputBoundary.java
src/main/java/use_case/user_login/UserLoginInteractor.java
src/main/java/use_case/user_login/UserLoginOutputBoundary.java
src/main/java/use_case/user_login/UserLoginOutputData.java

Implemented login controller and presenter

Login Interface Adapter

---

src/main/java/data_access/UserLoginDataAccessInterface.java
src/main/java/data_access/UserLoginDataAccessObject.java
src/main/java/use_case/user_login/UserLoginInteractor.java

changed some names/implementations for interactor and dao

Login Interactor Error

---

src/main/java/data_access/PrevPlanDataAccessInterface.java
src/main/java/data_access/PrevPlanDataAccessObject.java

Method is still incomplete and is not implementing the DataAccessInterface that it is associated with.

Add PrevPlanDataAccessObject functionality for reading csv files.

---

src/main/java/data_access/UserLoginDataAccessInterface.java
src/main/java/data_access/UserLoginDataAccessObject.java
src/main/java/interface_adapter/Login/LoginController.java
src/main/java/interface_adapter/Login/UserLoginFailed.java
src/main/java/use_case/user_login/UserLoginInputBoundary.java
src/main/java/use_case/user_login/UserLoginInputData.java
src/main/java/use_case/user_login/UserLoginInteractor.java
src/main/java/use_case/user_login/UserLoginOutputData.java

changed the logic of login interactor

Fixed Login Use Case

---

src/main/java/interface_adapter/Dayplan/DayplanPresenter.java
src/main/java/interface_adapter/Dayplan/DayplanState.java
src/main/java/interface_adapter/Dayplan/DayplanViewModel.java
src/main/java/interface_adapter/DayplanInput/DayplanInputPresenter.java
src/main/java/view/DayplanInputView.java
src/main/java/view/SignupView.java

Janice UI refined and entity test

---

src/main/java/app/UserLoginUseCaseFactory.java
src/main/java/interface_adapter/Login/LoginState.java
src/main/java/interface_adapter/Login/LoginViewManagerModel.java
src/main/java/interface_adapter/Login/LoginViewModel.java
src/main/java/interface_adapter/Login/UserLoginPresenter.java
src/main/java/use_case/user_login/UserLoginInteractor.java
src/main/java/view/LoginView.java

Changed implementation of presenter and interactor to handle errors with username and password. Made use case factory.

Login Update

---

src/main/java/app/Main.java
src/main/java/app/UserLoginUseCaseFactory.java
src/main/java/app/UserSignupUseCaseFactory.java
src/main/java/interface_adapter/Login/UserLoginPresenter.java
src/main/java/interface_adapter/Signup/SignupController.java
src/main/java/interface_adapter/Signup/SignupViewModel.java
src/main/java/view/SignupView.java

Main works again ver.2

---

src/main/java/app/DayplanInputUseCaseFactory.java
src/main/java/interface_adapter/Dayplan/DayplanController.java
src/main/java/interface_adapter/Dayplan/DayplanPresenter.java
src/main/java/interface_adapter/Dayplan/DayplanViewModel.java
src/main/java/use_case/refresh/RefreshInteractor.java
src/main/java/view/DayplanView.java

psvm at dayplanview.java is testing stuff

Dayplan UI semi-integration

---

pom.xml
src/test/java/app/UserLoginUseCaseFactoryTest.java
src/test/java/use_case/dayplanList/UserDayPlanInteractorTest.java
src/test/java/use_case/edit_info/EditInfoInteractorTest.java
src/test/java/use_case/previous_plan/PreviousPlanInteractorTest.java
src/test/java/use_case/refresh/RefreshInteractorTest.java
src/test/java/use_case/user_signup/UserSignupInteractorTest.java

Sign Up test started and added mockito dependency.

Set Up Use Case Testing + Mockito

---

src/test/java/data_access/DayPlanDataAccessObjectTest.java

Change test expected content for DayplanDAOTest

---

src/test/java/app/UserSignUpUseCaseFactoryTest.java
src/test/java/use_case/refresh/RefreshInteractorTest.java

Updated Refresh interactor test

Refresh Interactor Test

---

src/test/java/use_case/dayplanList/UserDayPlanInteractorTest.java

Added Interactor test for user day plan list, currently failing :((

Added User Day Plan Interactor Test
